# -*- coding: utf-8 -*-
"""sales_trend_analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kBjA3OALnpTFhoTTE104fAIXUlOOwbUc
"""

#Import libraries
import pandas as pd
import sqlite3

# Load the dataset
df = pd.read_csv("Sample - Superstore.csv", encoding='ISO-8859-1')

# Check a few rows
print(df.head())

#Check for null values
df.isnull().sum()

#Check for duplicates
df.duplicated().sum()

#Checking the data types
df.dtypes

# Convert Order Date to datetime
df['Order Date'] = pd.to_datetime(df['Order Date'])

df.dtypes

# Create SQLite in-memory DB
conn = sqlite3.connect(':memory:')
df.to_sql('orders', conn, index=False, if_exists='replace')

#Extract month from order_date
query_a = '''
SELECT
    "Order ID",
    "Order Date",
    strftime('%m', "Order Date") AS month
FROM orders
LIMIT 5
'''
print(pd.read_sql_query(query_a, conn))

#Group by year and month
query_b = '''
SELECT
    strftime('%Y', "Order Date") AS year,
    strftime('%m', "Order Date") AS month
FROM orders
GROUP BY year, month
LIMIT 5
'''
print(pd.read_sql_query(query_b, conn))

#Use SUM() for revenue
query_c = '''
SELECT
    strftime('%Y', "Order Date") AS year,
    strftime('%m', "Order Date") AS month,
    SUM(Sales) AS total_revenue
FROM orders
GROUP BY year, month
LIMIT 5
'''
print(pd.read_sql_query(query_c, conn))

#COUNT(DISTINCT order_id) for volume
query_d = '''
SELECT
    strftime('%Y', "Order Date") AS year,
    strftime('%m', "Order Date") AS month,
    COUNT(DISTINCT "Order ID") AS order_volume
FROM orders
GROUP BY year, month
LIMIT 5
'''
print(pd.read_sql_query(query_d, conn))

#Use ORDER BY for sorting
query_e = '''
SELECT
    strftime('%Y', "Order Date") AS year,
    strftime('%m', "Order Date") AS month,
    SUM(Sales) AS total_revenue,
    COUNT(DISTINCT "Order ID") AS order_volume
FROM orders
GROUP BY year, month
ORDER BY year, month
'''
print(pd.read_sql_query(query_e, conn))

#Limit results for specific time periods (e.g., only 2017)
query_f = '''
SELECT
    strftime('%Y', "Order Date") AS year,
    strftime('%m', "Order Date") AS month,
    SUM(Sales) AS total_revenue,
    COUNT(DISTINCT "Order ID") AS order_volume
FROM orders
WHERE strftime('%Y', "Order Date") = '2017'
GROUP BY year, month
ORDER BY month
'''
print(pd.read_sql_query(query_f, conn))

